name: Upload changes to back-end
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upload Json front-end
        if: contains(github.event.head_commit.message,'[back-end]') == false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ../
          git clone --depth 1 --single-branch --branch master https://github.com/yesC48/Sapphirium.git BackEndBranch
          python Sapphirium/.github/workflows/upload/front2back.py
          cd BackEndBranch
          git config --global user.email "firstcreator48@gmail.com"
          git config --global user.name "lconstr"
          git status --porcelain
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Json front-end update"
            git push https://yesC48:${{ secrets.SAPP_TOKEN }}@github.com/yesC48/Sapphirium
          fi
